FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:18

# Install Python
RUN apt-get update && apt-get install -y python3 python3-venv python3-pip git

# Set working directory
WORKDIR /workspace
